<?php
require_once __DIR__.'/session_workflow.php';
require_once __DIR__.'/session_presentation.php';
require_once __DIR__.'/retrieval.php';
if (!session_tracking_available($pdo)) {
    echo '<div class="alert alert-info">Session tracking is not available yet. Contact your administrator.</div>'; return;
}
$sessionState=session_state($pdo,(int)$doc['id']);
$sessionStage=$sessionState['stage'] ?? '';
$sessionLabels=session_stage_labels(); $sessionActions=session_action_labels();
$sessionEditable=session_can_manage($user) && !in_array($doc['records_status'],['Duplicate','Unauthorized Submission'],true);
$sessionDownload=can_download_record($user,$doc);
$sessionHistory=$pdo->prepare('SELECT e.*,u.full_name FROM document_session_events e LEFT JOIN users u ON u.id=e.actor_id WHERE e.document_id=? ORDER BY e.id DESC');
$sessionHistory->execute([$doc['id']]); $sessionEvents=$sessionHistory->fetchAll();
$sessionPosition=session_stage_position($sessionStage);
$sessionCompleted=session_stage_completed($sessionState);
$sessionChoices=$sessionEditable ? session_actions($sessionStage) : [];
if ($sessionEditable && $sessionStage==='amendment' && strtotime($sessionState['amendment_due_at'])<time()) $sessionChoices=['follow_up','receive_amendment'];
$sessionRetry=$_SESSION['session_form'] ?? [];
if ((int)($sessionRetry['document_id'] ?? 0)!==(int)$doc['id']) $sessionRetry=[];
else unset($_SESSION['session_form']);
$sessionPrimary=in_array($sessionRetry['action'] ?? '',$sessionChoices,true) ? $sessionRetry['action'] : ($sessionChoices[0] ?? '');
$sessionHelp=[
 'send_agenda'=>['Send within 24 hours of receipt. Delivery stays pending until you confirm the manual handoff.','Verification note / source reference','Metadata and attachments checked; ready for the next agenda.'],
 'confirm_delivery'=>['Use the reference from the actual handoff to the Agenda office.','Delivery reference and recipient','Transmittal no., receiving office/person, and delivery date.'],
 'receive_session'=>['Record the 1st-session return and register the private repository copy.','Receiving reference','Session date, receiving log number, and documents returned.'],
 'request_amendment'=>['Save after sending the request. The 15-calendar-day period starts now and Day 1 notifications are sent.','Dispatch reference and requested changes','Request no., recipient, and sections requiring amendment.'],
 'second_session'=>['Confirm that the documents can proceed to the 2nd session without amendments.','Session outcome / reference','Session minutes reference and outcome.'],
 'receive_amendment'=>['Attach the received amendment. Saving stops the outstanding amendment reminders.','Receipt and amendment details','Committee transmittal no., received date, and changes submitted.'],
 'follow_up'=>['Record who you contacted and their response. The original deadline stays on record.','Contact and response','Contact person, date/method, and expected submission.'],
 'third_session'=>['Continue when the 2nd session is complete and no further changes are required.','Review outcome / session reference','Reviewed amendment accepted; no further changes required.'],
 'upload_final'=>['Upload the official final PDF. Replacements keep earlier files in history; the latest is the printable hard-copy source.','Final document reference','Final version reference and preparation date.'],
];
$sessionEscape=static fn($value)=>htmlspecialchars((string)$value,ENT_QUOTES,'UTF-8');
?>
<link rel="stylesheet" href="assets/css/session-tracking.css?v=1">
<section class="session-workspace" aria-labelledby="session-heading">
 <header class="session-header"><div><p class="session-eyebrow">Document journey</p><h2 id="session-heading">Document Tracking</h2></div><span class="session-badge session-badge--<?= session_stage_tone($sessionStage,$sessionState) ?>"><i class="bi <?= $sessionCompleted ? 'bi-check-circle':'bi-circle-half' ?>" aria-hidden="true"></i><?= $sessionCompleted ? 'Completed' : 'Step '.($sessionPosition+1).' of 4' ?></span></header>
 <?php foreach (['session_success'=>'success','session_error'=>'danger'] as $key=>$style): if (!empty($_SESSION[$key])): ?><div class="alert alert-<?= $style ?> mx-3" role="<?= $style==='danger' ? 'alert':'status' ?>"><?= $sessionEscape($_SESSION[$key]) ?></div><?php unset($_SESSION[$key]); endif; endforeach; ?>
 <ol class="session-steps" aria-label="Document progress">
 <?php foreach (['Agenda','1st Session','2nd Session','3rd Session'] as $step=>$stepLabel): $completed=$step<$sessionPosition || $sessionCompleted; ?>
 <li class="<?= $completed ? 'is-complete':($step===$sessionPosition ? 'is-current':'') ?>" <?= !$completed && $step===$sessionPosition ? 'aria-current="step"':'' ?>><span class="session-step-number" aria-hidden="true"><?= $completed ? '<i class="bi bi-check-lg"></i>' : $step+1 ?></span><span><?= $stepLabel ?><small><?= $completed ? 'Complete':($step===$sessionPosition ? 'Current stage':'Upcoming') ?></small></span></li>
 <?php endforeach; ?></ol>
 <div class="session-current"><span class="session-current-icon"><i class="bi <?= $sessionCompleted ? 'bi-patch-check':'bi-signpost-split' ?>" aria-hidden="true"></i></span><div><h3><?= $sessionEscape($sessionLabels[$sessionStage] ?? 'Under Review') ?></h3><p><?= $sessionEscape(session_stage_hint($sessionStage)) ?></p></div></div>
 <?php if ($sessionStage==='' && ($agendaDue=session_agenda_due($doc,$sessionState))): $agendaNow=new DateTimeImmutable(); $agendaLate=$agendaDue<$agendaNow; $agendaSecs=$agendaDue->getTimestamp()-$agendaNow->getTimestamp(); $agendaStart=new DateTimeImmutable($doc['pending_since'] ?? $doc['received_at'] ?? $doc['created_at']); $agendaElapsed=max(0,min(24,(int)floor(($agendaNow->getTimestamp()-$agendaStart->getTimestamp())/3600))); ?>
 <div class="session-deadline <?= $agendaLate ? 'is-overdue':'' ?>"><div class="session-deadline-number"><strong><?= $agendaLate ? max(1,(int)ceil(-$agendaSecs/3600)) : max(0,(int)ceil($agendaSecs/3600)) ?></strong><span><?= $agendaLate ? 'hour(s) overdue':'hour(s) remaining' ?></span></div><div class="session-deadline-detail"><div class="session-section-heading"><h3><?= $agendaLate ? 'Agenda handoff overdue':'Send to Agenda within 24 hours' ?></h3><span class="session-badge session-badge--<?= $agendaLate ? 'danger':'warning' ?>"><?= $agendaLate ? 'Overdue — send now':((int)ceil($agendaSecs/3600)).'h left' ?></span></div><p>Received <?= $sessionEscape($agendaStart->format('M j, Y · g:i A')) ?> &middot; Due <strong><?= $sessionEscape($agendaDue->format('M j, Y · g:i A')) ?></strong></p><progress max="24" value="<?= $agendaElapsed ?>" aria-label="Elapsed hours of the 24-hour Agenda period"></progress><small>Hours from intake receipt, including weekends. Philippine time. Sending to Agenda stops this countdown.</small></div></div>
 <?php endif; ?>
 <?php if (in_array($sessionStage,['','agenda_pending'],true)): ?><p class="session-notice"><i class="bi bi-info-circle" aria-hidden="true"></i>Agenda delivery is manual for now. Preparing this handoff does not send the document to the other subsystem.</p><?php endif; ?>
 <?php if ($sessionStage==='amendment'): $due=new DateTimeImmutable($sessionState['amendment_due_at']); $started=new DateTimeImmutable($sessionState['amendment_started_at']); $now=new DateTimeImmutable(); $late=$due<$now; $remaining=max(0,(int)ceil(($due->getTimestamp()-$now->getTimestamp())/86400)); $elapsed=max(0,(int)floor(($now->getTimestamp()-$started->getTimestamp())/86400)); ?>
 <div class="session-deadline <?= $late ? 'is-overdue':'' ?>"><div class="session-deadline-number"><strong><?= $late ? max(1,(int)ceil(($now->getTimestamp()-$due->getTimestamp())/86400)) : $remaining ?></strong><span><?= $late ? 'day(s) overdue':'day(s) remaining' ?></span></div><div class="session-deadline-detail"><div class="session-section-heading"><h3><?= $late ? 'Committee follow-up needed':'15-day amendment period' ?></h3><span class="session-badge session-badge--<?= $late ? 'danger':'warning' ?>"><?= $late ? 'Overdue':'Day '.min(15,$elapsed+1).' of 15' ?></span></div><p>Sent <?= $sessionEscape($started->format('M j, Y')) ?> &middot; Due <strong><?= $sessionEscape($due->format('M j, Y · g:i A')) ?></strong></p><progress max="15" value="<?= min(15,$elapsed) ?>" aria-label="Elapsed days of the amendment period"></progress><small>Calendar days, including weekends. Philippine time. Reminders stop when the amendment is received.</small></div></div>
 <?php endif; ?>
 <?php if (in_array($sessionStage,['third_session','signed_pending','signed'],true)): ?><div class="session-files">
 <?php $finalId=!empty($sessionState['final_attachment_id']); ?>
 <article class="session-file-card"><i class="bi bi-file-earmark-pdf" aria-hidden="true"></i><div><div class="session-section-heading"><h3>Final PDF</h3><span class="session-file-status"><?= $finalId ? 'On file':'Not uploaded' ?></span></div><p>Download and print this copy as the hard copy.</p><?php if ($finalId && $sessionDownload): ?><a class="btn btn-outline-primary btn-sm" href="download_document.php?id=<?= (int)$doc['id'] ?>&amp;attachment=<?= (int)$sessionState['final_attachment_id'] ?>"><i class="bi bi-download" aria-hidden="true"></i> Download Final PDF</a><?php elseif ($finalId): ?><a class="small" href="copy_requests.php?document_id=<?= (int)$doc['id'] ?>&amp;from_document=<?= (int)$doc['id'] ?>">Request download access</a><?php else: ?><span class="small text-muted">Upload the official final PDF below.</span><?php endif; ?></div></article>
 <?php if (in_array($sessionStage,['signed_pending','signed'],true) && !empty($sessionState['signed_attachment_id'])): ?><article class="session-file-card"><i class="bi bi-file-earmark-check" aria-hidden="true"></i><div><div class="session-section-heading"><h3>Signed copy (legacy)</h3><span class="session-file-status"><?= $sessionStage==='signed' ? 'On file':'Pending check' ?></span></div><p>Scanned copy kept from before the signed-upload step was removed.</p><?php if ($sessionDownload): ?><a class="btn btn-outline-primary btn-sm" href="download_document.php?id=<?= (int)$doc['id'] ?>&amp;attachment=<?= (int)$sessionState['signed_attachment_id'] ?>"><i class="bi bi-download" aria-hidden="true"></i> Download Signed Copy</a><?php else: ?><a class="small" href="copy_requests.php?document_id=<?= (int)$doc['id'] ?>&amp;from_document=<?= (int)$doc['id'] ?>">Request download access</a><?php endif; ?></div></article><?php endif; ?>
 </div><?php endif; ?>
 <?php if ($sessionChoices): ?><div class="session-action-area"><div class="session-section-heading"><h3>Next action</h3><span class="session-helper">Choose the document’s next step</span></div><div class="session-action-list">
 <?php foreach ($sessionChoices as $sessionAction): $needsFile=in_array($sessionAction,['receive_amendment','upload_final'],true); [$actionHelp,$noteLabel,$noteHint]=$sessionHelp[$sessionAction]; $actionLabel=$sessionActions[$sessionAction]; if ($sessionAction==='upload_final' && !empty($sessionState['final_attachment_id'])) $actionLabel='Replace Final PDF'; $retryAction=($sessionRetry['action'] ?? '')===$sessionAction; ?>
 <details class="session-action" <?= $sessionAction===$sessionPrimary ? 'open':'' ?>><summary><span><i class="bi <?= $needsFile ? 'bi-cloud-arrow-up':($sessionAction==='request_amendment' ? 'bi-pencil-square':'bi-arrow-right-circle') ?>" aria-hidden="true"></i><?= $sessionEscape($actionLabel) ?></span><i class="bi bi-chevron-down session-chevron" aria-hidden="true"></i></summary>
 <form method="post" action="session_action.php" enctype="multipart/form-data" class="session-form" data-session-form>
 <?php csrf_field(); ?><input type="hidden" name="document_id" value="<?= (int)$doc['id'] ?>"><input type="hidden" name="revision" value="<?= (int)($sessionState['revision'] ?? 0) ?>"><input type="hidden" name="session_action" value="<?= $sessionAction ?>"><p class="session-action-help"><?= $sessionEscape($actionHelp) ?></p>
 <?php if ($sessionAction==='request_amendment'): ?><label class="form-label" for="amendment-committee">Receiving committee <span class="session-required">(required)</span></label><select id="amendment-committee" name="committee_id" class="form-select" required><option value="">Select a committee</option><?php foreach ($pdo->query('SELECT id,name FROM committees ORDER BY name')->fetchAll() as $committee): ?><option value="<?= (int)$committee['id'] ?>" <?= (int)($retryAction ? ($sessionRetry['committee_id'] ?? 0) : $doc['committee_id'])===(int)$committee['id'] ? 'selected':'' ?>><?= $sessionEscape($committee['name']) ?></option><?php endforeach; ?></select><?php endif; ?>
 <?php if ($needsFile || $sessionAction==='receive_session'): $fileLabel=$sessionAction==='receive_session' ? 'Returned session document (optional)' : ($sessionAction==='receive_amendment' ? 'Amended document' : 'Final PDF'); ?>
 <div class="session-upload"><label class="form-label" for="session-file-<?= $sessionAction ?>"><i class="bi bi-paperclip" aria-hidden="true"></i> <?= $fileLabel ?></label><input id="session-file-<?= $sessionAction ?>" type="file" name="session_file" class="form-control" aria-describedby="session-file-help-<?= $sessionAction ?>" accept="<?= in_array($sessionAction,['receive_amendment','receive_session'],true) ? '.pdf,.doc,.docx,.txt,.png,.jpg,.jpeg' : '.pdf' ?>" <?= $needsFile ? 'required':'' ?>><small id="session-file-help-<?= $sessionAction ?>"><?= in_array($sessionAction,['receive_amendment','receive_session'],true) ? 'PDF, Word, text, PNG or JPG':'PDF only' ?> &middot; Maximum 25 MB.<?= $retryAction ? ' Please select the file again.':'' ?></small></div><?php endif; ?>
 <label class="form-label" for="session-note-<?= $sessionAction ?>"><?= $sessionEscape($noteLabel) ?> <span class="session-required">(required)</span></label><textarea id="session-note-<?= $sessionAction ?>" class="form-control" name="note" maxlength="4000" rows="3" placeholder="<?= $sessionEscape($noteHint) ?>" required><?= $retryAction ? $sessionEscape($sessionRetry['note'] ?? ''):'' ?></textarea><div class="session-form-footer"><span class="session-helper">Saved to the document’s activity history.</span><button type="submit" class="btn btn-primary"><span data-submit-label><?= $sessionEscape($actionLabel) ?></span> <i class="bi bi-arrow-right" aria-hidden="true"></i></button></div><p class="session-form-status" role="status" aria-live="polite"></p>
 </form></details><?php endforeach; ?></div></div>
 <?php elseif (!$sessionEditable && !$sessionCompleted): ?><p class="session-notice"><i class="bi bi-lock" aria-hidden="true"></i><?= in_array($doc['records_status'],['Duplicate','Unauthorized Submission'],true) ? 'This submission is closed. Session actions are unavailable.':'You can view this workflow. Staff with records validation permission can update it.' ?></p><?php endif; ?>
 <details class="session-history" <?= !$sessionChoices ? 'open':'' ?>><summary><span><i class="bi bi-clock-history" aria-hidden="true"></i> Activity &amp; file history <span class="session-history-count"><?= count($sessionEvents) ?></span></span><i class="bi bi-chevron-down session-chevron" aria-hidden="true"></i></summary><?php if (!$sessionEvents): ?><div class="session-history-empty">No session activity yet. The first handoff will appear here.</div><?php endif; ?><ol class="session-timeline">
 <?php foreach ($sessionEvents as $event): ?><li><div class="session-timeline-dot" aria-hidden="true"></div><div><strong><?= $sessionEscape($sessionActions[$event['action']] ?? 'Overdue reminder') ?></strong><p class="session-helper"><time datetime="<?= $sessionEscape(date('c',strtotime($event['created_at']))) ?>"><?= $sessionEscape(date('M j, Y · g:i A',strtotime($event['created_at']))) ?></time> &middot; <?= $sessionEscape($event['full_name'] ?: 'System') ?></p><p class="session-timeline-note"><?= nl2br($sessionEscape($event['note'])) ?></p><?php if ($event['attachment_id'] && $sessionDownload): ?><a class="session-history-download" href="download_document.php?id=<?= (int)$doc['id'] ?>&amp;attachment=<?= (int)$event['attachment_id'] ?>"><i class="bi bi-download" aria-hidden="true"></i> Download this version</a><?php endif; ?></div></li><?php endforeach; ?></ol>
 </details>
</section>
<script src="assets/js/session-tracking.js?v=1" defer></script>
